### ISSUE TITLE
When send korean word to input, This Error printed

### ISSUE THREAD

**Issue by kjongdae** [kreneskyp/ix#103]
When send korean word to input, This Error printed

I think langchain does'nt support multi language

`
Unexpected Application Error!
Cannot resolve a DOM point from Slate point: {"path":[0,0],"offset":2}
Error: Cannot resolve a DOM point from Slate point: {"path":[0,0],"offset":2}
    at Object.toDOMPoint (webpack-internal:///./node_modules/slate-react/dist/index.es.js:736:13)
    at Object.toDOMRange (webpack-internal:///./node_modules/slate-react/dist/index.es.js:747:33)
    at setDomSelection (webpack-internal:///./node_modules/slate-react/dist/index.es.js:3366:50)
    at eval (webpack-internal:///./node_modules/slate-react/dist/index.es.js:3383:23)
    at commitHookEffectListMount (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:23145:26)
    at commitLayoutEffectOnFiber (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:23268:15)
    at commitLayoutMountEffects_complete (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:24683:9)
    at commitLayoutEffects_begin (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:24669:7)
    at commitLayoutEffects_begin (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:24651:11)
    at commitLayoutEffects (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:24607:3)
💿 Hey developer 👋

You can provide a way better UX than this when your app throws errors by providing your own ErrorBoundary or errorElement prop on your route.`

**Comment by kreneskyp** [comment]
A basic test shows the model can understand and respond in korean.  I don't speak korean so I used google translate.
![image](https://github.com/kreneskyp/ix/assets/68635/6f97d65b-2373-4dde-935f-3fbaeb9c8cc4)

>  DEBUG Moderator returned response=안녕하세요! 어떻게 도와드릴까요?

The console log shows the model did return a response in your case too.  The error indicates the UI had trouble rendering something within the chat input box. Slate.js is only used in the chat input right now.

Did the error occur while you were typing in the chat box?

**Comment by kreneskyp** [comment]
After further investigation the issue is not related to language used. I consistently replicated this error with english characters.

**Steps to replicate:**
1. Send a message
2. Send a second message before the first has finished rendering.

**Workaround:**
1. refresh the browser page.
