### ISSUE TITLE
Database error on dev_setup

### ISSUE THREAD

**Issue by aatimofeev** [kreneskyp/ix#81]
Hey! The project looks really promising!

However, I'm getting the following error every time I try to follow instructions in the README:
```
django.db.utils.IntegrityError: Problem installing fixtures: insert or update on table "chains_chainnode" violates foreign key constraint "chains_chainnode_node_type_id_506db102_fk_chains_nodetype_id"
DETAIL:  Key (node_type_id)=(7fff77c2-7ccc-4493-9f2b-54244c3d15e0) is not present in table "chains_nodetype".
```
`node_type_id` is the same on every attempt

**Comment by kreneskyp** [comment]
Thanks for the bug report. Looking into this now.

Could you post the log  just prior to this error? Thanks!

**Comment by kreneskyp** [comment]
I was able to reproduce the bug.  There was an error with the fixture setup. 

Fix here: 

```
Creating ix_web_run ... done
Updating component: langchain.embeddings.openai.OpenAIEmbeddings
Updating component: langchain.embeddings.google_palm.GooglePalmEmbeddings
Updating component: langchain.embeddings.llama_cpp.LlamaCppEmbeddings
Updating component: langchain.embeddings.vertexai.VertexAIEmbeddings
Updating component: langchain.embeddings.huggingface.HuggingFaceEmbeddings
Updating component: langchain.embeddings.mosaicml.MosaicMLInstructorEmbeddings
Updating component: ix.chains.loaders.agents.initialize_openai_functions
Updating component: ix.chains.loaders.agents.initialize_openai_multi_functions
Updating component: ix.chains.loaders.agents.initialize_zero_shot_react_description
Updating component: ix.chains.loaders.agents.initialize_react_docstore
Updating component: ix.chains.loaders.agents.initialize_self_ask_with_search
Updating component: ix.chains.loaders.agents.initialize_conversational_react_description
Updating component: ix.chains.loaders.agents.initialize_chat_zero_shot_react_description
Updating component: ix.chains.loaders.agents.initialize_chat_conversational_react_description
Updating component: ix.chains.loaders.agents.initialize_structured_chat_zero_shot_react_description
Updating component: ix.tools.google.get_google_search
Updating component: ix.tools.wolfram_alpha.get_wolfram_alpha
Updating component: langchain.chat_models.openai.ChatOpenAI
Updating component: langchain.chat_models.google_palm.ChatGooglePalm
Updating component: langchain.chat_models.anthropic.ChatAnthropic
Updating component: ix.chains.llm_chain.LLMChain
Updating component: ix.chains.tool_chain.LLMToolChain
Updating component: ix.chains.llm_chain.LLMReply
Updating component: langchain.chains.SequentialChain
Updating component: ix.chains.routing.MapSubchain
Updating component: ix.chains.functions.FunctionSchema
Updating component: ix.chains.functions.OpenAIFunctionParser
Updating component: langchain.prompts.chat.ChatPromptTemplate
Updating component: langchain.memory.ConversationBufferMemory
Updating component: langchain.memory.buffer_window.ConversationBufferWindowMemory
Updating component: langchain.memory.summary_buffer.ConversationSummaryBufferMemory
Updating component: langchain.memory.token_buffer.ConversationTokenBufferMemory
Updating component: langchain.memory.RedisChatMessageHistory
Updating component: langchain.memory.chat_message_histories.file.FileChatMessageHistory
Updating component: langchain.vectorstores.Redis
Updating component: ix.chains.moderator.ChatModerator
Updating component: ix.memory.artifacts.ArtifactMemory
Updating component: ix.chains.artifacts.SaveArtifact
Updating component: ix.chains.tests.mock_memory.MockMemory
Updating component: ix.chains.tests.mock_chain.MockChain
docker-compose run --rm web ./manage.py loaddata ix_v2 code_v2 pirate_v1
Creating ix_web_run ... done
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/psycopg/cursor.py", line 723, in execute
    raise ex.with_traceback(None)
django.db.utils.IntegrityError: Problem installing fixtures: insert or update on table "chains_chainnode" violates foreign key constraint "chains_chainnode_node_type_id_506db102_fk_chains_nodetyp
e_id"
DETAIL:  Key (node_type_id)=(7fff77c2-7ccc-4493-9f2b-54244c3d15e0) is not present in table "chains_nodetype".
ERROR: 1
make: *** [Makefile:164: dev_fixtures] Error 1
```

**Comment by kreneskyp** [comment]
Just merged a fix! Please let me know if there are any remaining issues!
